[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#6C3FB6"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#16161a"
textColor = "#F8F8F2" 