# Streamlit Secrets Configuration
# Copy this file to .streamlit/secrets.toml and add your actual API key
# For local development, you can also use a .env file

OPENROUTER_API_KEY = "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" 